=== JulenCuadra/GCIS_Fog/Factory_elements/SystemModelComponent/XML/ComponentList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2020 (http://www.altova.com) by  (University of the Basque Country) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<!-- ============== DEFINITION OF DATA TYPES ============= -->
	<xs:complexType name="TPlant">
		<xs:attribute name="machineId" type="xs:string" use="required"/>
		<xs:attribute name="orderId" type="xs:string" use="required"/>
		<xs:attribute name="batchId" type="xs:string" use="required"/>
		<xs:attribute name="itemID" type="xs:string" use="required"/>
		<xs:attribute name="serviceTypeId" type="xs:string" use="required"/>
		<xs:attribute name="subproductTypeId" type="xs:string" use="required"/>
		<xs:attribute name="dataInitialTimeStamp" type="xs:dateTime" use="required"/>
		<xs:attribute name="dataFinalTimeStamp" type="xs:dateTime" use="required"/>
		<xs:attribute name="dataServiceTimeStamp" type="xs:dateTime" use="required"/>
		<!-- YYYY-MM-DDThh:mm:ss -->
	</xs:complexType>
	<xs:complexType name="Times">
		<xs:attribute name="itemId" type="xs:string" use="required"/>
		<xs:attribute name="actionId" type="xs:string" use="required"/>
		<xs:attribute name="start" type="xs:time" use="required"/>
		<xs:attribute name="finish" type="xs:time" use="required"/>
	</xs:complexType>
	<xs:complexType name="TDataBase">
		<xs:sequence>
			<xs:element name="plannedTimes">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="plannedTime" type="Times"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="actualTimes">
				<xs:complexType>
					<xs:sequence minOccurs="1" maxOccurs="unbounded">
						<xs:element name="actualTime" type="Times"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="machineId" type="xs:string" use="required"/>
		<xs:attribute name="actionId" type="xs:string" use="required"/>
		<xs:attribute name="itemId" type="xs:string" use="required"/>
		<xs:attribute name="start" type="xs:time" use="required"/>
		<xs:attribute name="finish" type="xs:time" use="required"/>
	</xs:complexType>
	<xs:simpleType name="DataType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TPlant"/>
			<xs:enumeration value="TDataBase"/>
			<xs:enumeration value="Bool"/>
			<xs:enumeration value="ShortInt"/>
			<xs:enumeration value="Int"/>
			<xs:enumeration value="String"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- =========== FINISH OF DATA TYPE DIFINITIONS =============== -->
	<xs:complexType name="Parameter">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="type" type="DataType" use="required"/>		
	</xs:complexType>
	<xs:element name="function">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="input" type="Parameter" minOccurs="0" maxOccurs="1"/>
				<xs:element name="output" type="Parameter" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="protocol">
		<xs:complexType>
			<xs:attribute name="in" type="xs:string" use="optional"/>
			<xs:attribute name="out" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="TComponent">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SOURCE_PLANT_MQTT"/>
			<xs:enumeration value="SINK_EXIST"/>
			<xs:enumeration value="SOURCE_PROCESSING_DB"/>
			<xs:enumeration value="PROCESSING_OEE"/>
			<xs:enumeration value="EVENT_MANAGER"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:group name="Data">
		<xs:choice>
			<xs:element name="TPlant" type="TPlant"/>
			<xs:element name="TDataBase" type="TDataBase"/>
		</xs:choice>
	</xs:group>
	<xs:element name="component">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="function" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element ref="protocol" minOccurs="1" maxOccurs="1"/>
				<xs:group ref="Data" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="type" type="TComponent" use="required"/>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="componentList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="component" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JulenCuadra/GCIS_Fog/Factory_elements/SystemModelComponent/XML/ComponentList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2020 (http://www.altova.com) by  (University of the Basque Country) -->
<componentList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/eestevez/Downloads/ComponentList.xsd">
	<component type="SOURCE_PLANT_MQTT" id="gcr.io/gcis/source:mqtt" name="GetDataFromPlant" description="description of component">
		<function name="get_plant_data" description="description of function">
			<output name="out1" type="TPlant" protocol="http"/>
		</function>
	</component>
	<component type="SINK_EXIST" id="gcr.io/gcis/sink:exist" name="StoreDataInDB" description="description of component">
		<function name="updateProductInstance" description="description of function">
			<input name="in1" type="TPlant" protocol="http"/>
		</function>
	</component>
	<component type="SOURCE_PROCESSING_DB" id="gcr.io/gcis/source:exist" name="GetDataFromDB" description="description of component">
		<function name="get_eXist" description="description of function">
			<output name="out1" type="TDataBase" protocol="http"/>
		</function>
	</component>
	<component type="PROCESSING_OEE" id="gcr.io/gcis/processing:oee" name="ProcessData" description="description of component">
		<function name="OEEComputing" description="description of function">
			<input name="in1" type="TDataBase" protocol="http"/>
			<output name="out1" type="String" protocol="http"/>
		</function>
	</component>
	<component type="EVENT_MANAGER" id="gcr.io/gcis/factoryComponent:eventManager" name="EventManager" description="description of component">
		<function name="operatorAlarm" description="description of function">
			<input name="in1" type="String" protocol="http"/>
		</function>
	</component>
</componentList>
